import { Injectable } from "@angular/core";
import { CountryRegion } from "../data-structures/models/CountryRegion";

@Injectable({
    providedIn: 'root'
  })

export class CountryRegionService {

    private countryRegions : CountryRegion[] = [];

    constructor(){
        this.populateCountryRegions();
    }

    public getCountryRegions() : CountryRegion[]
    {
        return this.countryRegions;
    }

    private populateCountryRegions(){
        this.countryRegions =  [
            new CountryRegion(1, 'US', 'United States' ),
            new CountryRegion(2, 'CA', 'Canada' ),
            new CountryRegion(3, 'VI', 'Virgin Islands, U.S.' ),
            new CountryRegion(11, 'AF', 'Afghanistan' ),
            new CountryRegion(12, 'AL', 'Albania' ),
            new CountryRegion(13, 'DZ', 'Algeria' ),
            new CountryRegion(14, 'AS', 'American Samoa' ),
            new CountryRegion(15, 'AD', 'Andorra' ),
            new CountryRegion(16, 'AO', 'Angola' ),
            new CountryRegion(17, 'AI', 'Anguilla' ),
            new CountryRegion(18, 'AQ', 'Antarctica' ),
            new CountryRegion(19, 'AG', 'Antigua and Barbuda' ),
            new CountryRegion(20, 'AR', 'Argentina' ),
            new CountryRegion(21, 'AM', 'Armenia' ),
            new CountryRegion(22, 'AW', 'Aruba' ),
            new CountryRegion(23, 'AU', 'Australia' ),
            new CountryRegion(24, 'AT', 'Austria' ),
            new CountryRegion(25, 'AZ', 'Azerbaijan' ),
            new CountryRegion(26, 'BS', 'Bahamas, The' ),
            new CountryRegion(27, 'BH', 'Bahrain' ),
            new CountryRegion(28, 'BD', 'Bangladesh' ),
            new CountryRegion(29, 'BB', 'Barbados' ),
            new CountryRegion(30, 'BY', 'Belarus' ),
            new CountryRegion(31, 'BE', 'Belgium' ),
            new CountryRegion(32, 'BZ', 'Belize' ),
            new CountryRegion(33, 'BJ', 'Benin' ),
            new CountryRegion(34, 'BM', 'Bermuda' ),
            new CountryRegion(35, 'BT', 'Bhutan' ),
            new CountryRegion(36, 'BO', 'Bolivia' ),
            new CountryRegion(37, 'BA', 'Bosnia and Herzegovina' ),
            new CountryRegion(38, 'BW', 'Botswana' ),
            new CountryRegion(39, 'BV', 'Bouvet Island' ),
            new CountryRegion(40, 'BR', 'Brazil' ),
            new CountryRegion(41, 'IO', 'British Indian Ocean Territory' ),
            new CountryRegion(42, 'BN', 'Brunei' ),
            new CountryRegion(43, 'BG', 'Bulgaria' ),
            new CountryRegion(44, 'BF', 'Burkina Faso' ),
            new CountryRegion(45, 'BI', 'Burundi' ),
            new CountryRegion(46, 'KH', 'Cambodia' ),
            new CountryRegion(47, 'CM', 'Cameroon' ),
            new CountryRegion(48, 'CV', 'Cape Verde' ),
            new CountryRegion(49, 'KY', 'Cayman Islands' ),
            new CountryRegion(50, 'CF', 'Central African Republic' ),
            new CountryRegion(51, 'TD', 'Chad' ),
            new CountryRegion(52, 'CL', 'Chile' ),
            new CountryRegion(53, 'CN', 'China' ),
            new CountryRegion(54, 'CX', 'Christmas Island' ),
            new CountryRegion(55, 'CC', 'Cocos (Keeling) Islands' ),
            new CountryRegion(56, 'CO', 'Colombia' ),
            new CountryRegion(57, 'KM', 'Comoros' ),
            new CountryRegion(58, 'CG', 'Congo' ),
            new CountryRegion(59, 'CD', 'Congo (DRC)' ),
            new CountryRegion(60, 'CK', 'Cook Islands' ),
            new CountryRegion(61, 'CR', 'Costa Rica' ),
            new CountryRegion(62, 'CI', 'Côte d''Ivoire' ),
            new CountryRegion(63, 'HR', 'Croatia' ),
            new CountryRegion(64, 'CU', 'Cuba' ),
            new CountryRegion(65, 'CY', 'Cyprus' ),
            new CountryRegion(66, 'CZ', 'Czech Republic' ),
            new CountryRegion(67, 'DK', 'Denmark' ),
            new CountryRegion(68, 'DJ', 'Djibouti' ),
            new CountryRegion(69, 'DM', 'Dominica' ),
            new CountryRegion(70, 'DO', 'Dominican Republic' ),
            new CountryRegion(71, 'EC', 'Ecuador' ),
            new CountryRegion(72, 'EG', 'Egypt' ),
            new CountryRegion(73, 'SV', 'El Salvador' ),
            new CountryRegion(74, 'GQ', 'Equatorial Guinea' ),
            new CountryRegion(75, 'ER', 'Eritrea' ),
            new CountryRegion(76, 'EE', 'Estonia' ),
            new CountryRegion(77, 'ET', 'Ethiopia' ),
            new CountryRegion(78, 'FK', 'Falkland Islands (Islas Malvinas)' ),
            new CountryRegion(79, 'FO', 'Faroe Islands' ),
            new CountryRegion(80, 'FJ', 'Fiji Islands' ),
            new CountryRegion(81, 'FI', 'Finland' ),
            new CountryRegion(82, 'FR', 'France' ),
            new CountryRegion(83, 'GF', 'French Guiana' ),
            new CountryRegion(84, 'PF', 'French Polynesia' ),
            new CountryRegion(85, 'TF', 'French Southern and Antarctic Lands' ),
            new CountryRegion(86, 'GA', 'Gabon' ),
            new CountryRegion(87, 'GM', 'Gambia, The' ),
            new CountryRegion(88, 'GE', 'Georgia' ),
            new CountryRegion(89, 'DE', 'Germany' ),
            new CountryRegion(90, 'GH', 'Ghana' ),
            new CountryRegion(91, 'GI', 'Gibraltar' ),
            new CountryRegion(92, 'GR', 'Greece' ),
            new CountryRegion(93, 'GL', 'Greenland' ),
            new CountryRegion(94, 'GD', 'Grenada' ),
            new CountryRegion(95, 'GP', 'Guadeloupe' ),
            new CountryRegion(96, 'GU', 'Guam' ),
            new CountryRegion(97, 'GT', 'Guatemala' ),
            new CountryRegion(98, 'GN', 'Guinea' ),
            new CountryRegion(99, 'GW', 'Guinea-Bissau' ),
            new CountryRegion(100, 'GY', 'Guyana' ),
            new CountryRegion(101, 'HT', 'Haiti' ),
            new CountryRegion(102, 'HM', 'Heard Island and McDonald Islands' ),
            new CountryRegion(103, 'HN', 'Honduras' ),
            new CountryRegion(104, 'HK', 'Hong Kong SAR' ),
            new CountryRegion(105, 'HU', 'Hungary' ),
            new CountryRegion(106, 'IS', 'Iceland' ),
            new CountryRegion(107, 'IN', 'India' ),
            new CountryRegion(108, 'ID', 'Indonesia' ),
            new CountryRegion(109, 'IR', 'Iran' ),
            new CountryRegion(110, 'IQ', 'Iraq' ),
            new CountryRegion(111, 'IE', 'Ireland' ),
            new CountryRegion(112, 'IL', 'Israel' ),
            new CountryRegion(113, 'IT', 'Italy' ),
            new CountryRegion(114, 'JM', 'Jamaica' ),
            new CountryRegion(115, 'JP', 'Japan' ),
            new CountryRegion(116, 'JO', 'Jordan' ),
            new CountryRegion(117, 'KZ', 'Kazakhstan' ),
            new CountryRegion(118, 'KE', 'Kenya' ),
            new CountryRegion(119, 'KI', 'Kiribati' ),
            new CountryRegion(120, 'KR', 'Korea' ),
            new CountryRegion(121, 'KW', 'Kuwait' ),
            new CountryRegion(122, 'KG', 'Kyrgyzstan' ),
            new CountryRegion(123, 'LA', 'Laos' ),
            new CountryRegion(124, 'LV', 'Latvia' ),
            new CountryRegion(125, 'LB', 'Lebanon' ),
            new CountryRegion(126, 'LS', 'Lesotho' ),
            new CountryRegion(127, 'LR', 'Liberia' ),
            new CountryRegion(128, 'LY', 'Libya' ),
            new CountryRegion(129, 'LI', 'Liechtenstein' ),
            new CountryRegion(130, 'LT', 'Lithuania' ),
            new CountryRegion(131, 'LU', 'Luxembourg' ),
            new CountryRegion(132, 'MO', 'Macao SAR' ),
            new CountryRegion(133, 'MK', 'Macedonia, Former Yugoslav Republic of' ),
            new CountryRegion(134, 'MG', 'Madagascar' ),
            new CountryRegion(135, 'MW', 'Malawi' ),
            new CountryRegion(136, 'MY', 'Malaysia' ),
            new CountryRegion(137, 'MV', 'Maldives' ),
            new CountryRegion(138, 'ML', 'Mali' ),
            new CountryRegion(139, 'MT', 'Malta' ),
            new CountryRegion(140, 'MH', 'Marshall Islands' ),
            new CountryRegion(141, 'MQ', 'Martinique' ),
            new CountryRegion(142, 'MR', 'Mauritania' ),
            new CountryRegion(143, 'MU', 'Mauritius' ),
            new CountryRegion(144, 'YT', 'Mayotte' ),
            new CountryRegion(145, 'MX', 'Mexico' ),
            new CountryRegion(146, 'FM', 'Micronesia' ),
            new CountryRegion(147, 'MD', 'Moldova' ),
            new CountryRegion(148, 'MC', 'Monaco' ),
            new CountryRegion(149, 'MN', 'Mongolia' ),
            new CountryRegion(150, 'MS', 'Montserrat' ),
            new CountryRegion(151, 'MA', 'Morocco' ),
            new CountryRegion(152, 'MZ', 'Mozambique' ),
            new CountryRegion(153, 'MM', 'Myanmar' ),
            new CountryRegion(154, 'NA', 'Namibia' ),
            new CountryRegion(155, 'NR', 'Nauru' ),
            new CountryRegion(156, 'NP', 'Nepal' ),
            new CountryRegion(157, 'NL', 'Netherlands' ),
            new CountryRegion(158, 'AN', 'Netherlands Antilles' ),
            new CountryRegion(159, 'NC', 'New Caledonia' ),
            new CountryRegion(160, 'NZ', 'New Zealand' ),
            new CountryRegion(161, 'NI', 'Nicaragua' ),
            new CountryRegion(162, 'NE', 'Niger' ),
            new CountryRegion(163, 'NG', 'Nigeria' ),
            new CountryRegion(164, 'NU', 'Niue' ),
            new CountryRegion(165, 'NF', 'Norfolk Island' ),
            new CountryRegion(166, 'KP', 'North Korea' ),
            new CountryRegion(167, 'MP', 'Northern Mariana Islands' ),
            new CountryRegion(168, 'NO', 'Norway' ),
            new CountryRegion(169, 'OM', 'Oman' ),
            new CountryRegion(170, 'PK', 'Pakistan' ),
            new CountryRegion(171, 'PW', 'Palau' ),
            new CountryRegion(172, 'PS', 'Palestinian Authority' ),
            new CountryRegion(173, 'PA', 'Panama' ),
            new CountryRegion(174, 'PG', 'Papua New Guinea' ),
            new CountryRegion(175, 'PY', 'Paraguay' ),
            new CountryRegion(176, 'PE', 'Peru' ),
            new CountryRegion(177, 'PH', 'Philippines' ),
            new CountryRegion(178, 'PN', 'Pitcairn Islands' ),
            new CountryRegion(179, 'PL', 'Poland' ),
            new CountryRegion(180, 'PT', 'Portugal' ),
            new CountryRegion(181, 'PR', 'Puerto Rico' ),
            new CountryRegion(182, 'QA', 'Qatar' ),
            new CountryRegion(183, 'RE', 'Réunion' ),
            new CountryRegion(184, 'RO', 'Romania' ),
            new CountryRegion(185, 'RU', 'Russia' ),
            new CountryRegion(186, 'RW', 'Rwanda' ),
            new CountryRegion(187, 'SH', 'Saint Helena' ),
            new CountryRegion(188, 'KN', 'Saint Kitts and Nevis' ),
            new CountryRegion(189, 'LC', 'Saint Lucia' ),
            new CountryRegion(190, 'PM', 'Saint Pierre and Miquelon' ),
            new CountryRegion(191, 'VC', 'Saint Vincent and the Grenadine' ),
            new CountryRegion(192, 'WS', 'Samoa' ),
            new CountryRegion(193, 'SM', 'San Marino' ),
            new CountryRegion(194, 'ST', 'São Tomé and Príncipe' ),
            new CountryRegion(195, 'SA', 'Saudi Arabia' ),
            new CountryRegion(196, 'SN', 'Senegal' ),
            new CountryRegion(197, 'CS', 'Serbia and Montenegro' ),
            new CountryRegion(198, 'SC', 'Seychelles' ),
            new CountryRegion(199, 'SL', 'Sierra Leone' ),
            new CountryRegion(200, 'SG', 'Singapore' ),
            new CountryRegion(201, 'SK', 'Slovakia' ),
            new CountryRegion(202, 'SI', 'Slovenia' ),
            new CountryRegion(203, 'SB', 'Solomon Islands' ),
            new CountryRegion(204, 'SO', 'Somalia' ),
            new CountryRegion(205, 'ZA', 'South Africa' ),
            new CountryRegion(206, 'GS', 'South Georgia and the South Sandwich Islands' ),
            new CountryRegion(207, 'ES', 'Spain' ),
            new CountryRegion(208, 'LK', 'Sri Lanka' ),
            new CountryRegion(209, 'SD', 'Sudan' ),
            new CountryRegion(210, 'SR', 'Suriname' ),
            new CountryRegion(211, 'SJ', 'Svalbard and Jan Mayen' ),
            new CountryRegion(212, 'SZ', 'Swaziland' ),
            new CountryRegion(213, 'SE', 'Sweden' ),
            new CountryRegion(214, 'CH', 'Switzerland' ),
            new CountryRegion(215, 'SY', 'Syria' ),
            new CountryRegion(216, 'TW', 'Taiwan' ),
            new CountryRegion(217, 'TJ', 'Tajikistan' ),
            new CountryRegion(218, 'TZ', 'Tanzania' ),
            new CountryRegion(219, 'TH', 'Thailand' ),
            new CountryRegion(220, 'TL', 'Timor-Leste' ),
            new CountryRegion(221, 'TG', 'Togo' ),
            new CountryRegion(222, 'TK', 'Tokelau' ),
            new CountryRegion(223, 'TO', 'Tonga' ),
            new CountryRegion(224, 'TT', 'Trinidad and Tobago' ),
            new CountryRegion(225, 'TN', 'Tunisia' ),
            new CountryRegion(226, 'TR', 'Turkey' ),
            new CountryRegion(227, 'TM', 'Turkmenistan' ),
            new CountryRegion(228, 'TC', 'Turks and Caicos Islands' ),
            new CountryRegion(229, 'TV', 'Tuvalu' ),
            new CountryRegion(230, 'UM', 'U.S. Minor Outlying Islands' ),
            new CountryRegion(231, 'UG', 'Uganda' ),
            new CountryRegion(232, 'UA', 'Ukraine' ),
            new CountryRegion(233, 'AE', 'United Arab Emirates' ),
            new CountryRegion(234, 'GB', 'United Kingdom' ),
            new CountryRegion(235, 'UY', 'Uruguay' ),
            new CountryRegion(236, 'UZ', 'Uzbekistan' ),
            new CountryRegion(237, 'VU', 'Vanuatu' ),
            new CountryRegion(238, 'VA', 'Vatican City' ),
            new CountryRegion(239, 'VE', 'Venezuela' ),
            new CountryRegion(240, 'VN', 'Vietnam' ),
            new CountryRegion(241, 'VG', 'Virgin Islands, British' ),
            new CountryRegion(242, 'WF', 'Wallis and Futuna' ),
            new CountryRegion(243, 'YE', 'Yemen' ),
            new CountryRegion(244, 'ZM', 'Zambia' ),
            new CountryRegion(245, 'ZW', 'Zimbabwe' )
        ]
    }
}